# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = ["model.py"]

doc_url = "https://Taphei.github.io/ml_project_template_test_tapani/"

git_url = "https://github.com/Taphei/ml_project_template_test_tapani/tree/master/"

def custom_doc_links(name): return None
